### ISSUE TITLE
Behavior not /quite/ the same as `new Notification`

### ISSUE THREAD

**Issue by bengotow** [CharlieHess/node-mac-notifier#11]
We discovered today (the hard way, after shipping an update!) that node-mac-notifier isn't quite an equivalent replacement for Electron's `new Notification` API. If you repeatedly call `new Notification` with the same notification tag, it displays the notification again each time. If you repeatedly call `new NodeMacNotification...` with the same `id`, the notification is not re-displayed. To make the notification show again, you must first `close()` the previous notification with the same tag.

I don't think this is a big deal - we fixed it in N1 by keeping a lookup table of notifications and calling close ourselves before re-displaying the notification. It might be good to mention in the docs though!

https://github.com/nylas/N1/commit/0c378f83feed7da55df775d08491039dee9163fa

**Comment by Kronenberg** [comment]
@bengotow i am trying to run node-mac-notifier module in https://github.com/chentsulin/electron-react-boilerplate
I am using your code example from nylus, but have this error.
The problem with dependencies inside the module, but nylus is Electron project, how you solve it?

![screen shot 2018-01-16 at 11 38 19 am](https://user-images.githubusercontent.com/13053374/34982306-b84d7778-fab2-11e7-8a12-234cdef2b8d8.png)

**Comment by bengotow** [comment]
Hey @Kronenberg — hmm, that error doesn't seem related to this issue, I'd file a bug with electron-react-boilerplate, it looks like you either haven't compiled the native code in `node-mac-notifier`, or some sort of hot module reloading / path issue is interfering with the resolution of `bindings.js` within the module.

**Comment by Kronenberg** [comment]
@bengotow ye i fix it, was compile error + i am install binding module separately.
 Btw,  Nylus client looks really cool! I will use it! :) Great app!

**Comment by CharlieHess** [comment]
@bengotow thanks for the heads-up. The `id` option is more clearly documented now.
