### ISSUE TITLE
warning node-mac-notifier > node-uuid@1.4.8: Use uuid module instead

### ISSUE THREAD

**Issue by marmos91** [CharlieHess/node-mac-notifier#15]
When installing with node 8.6.0 npm rise this warning.
`warning node-mac-notifier > node-uuid@1.4.8: Use uuid module instead`

**Comment by HappyTobi** [comment]
I fixed that, but we have to wait till the pull request was accepted
[Pull request](https://github.com/CharlieHess/node-mac-notifier/pull/20)

**Comment by CharlieHess** [comment]
This is fixed in `1.0.0`, thanks Tobi.
