### ISSUE TITLE
[Question] Add action buttons to notification

### ISSUE THREAD

**Issue by clusterberries** [CharlieHess/node-mac-notifier#16]
Hi all! 
Is there any chance to add action buttons to notifications?
I mean like this one:
![image](https://user-images.githubusercontent.com/9727404/34383477-7c6b22b4-eb26-11e7-9751-240da1fbd8f8.png)

**Comment by ccnokes** [comment]
Looks like you can do that now in core electron. See https://github.com/electron/electron/blob/master/docs/api/structures/notification-action.md and https://github.com/electron/electron/blob/master/docs/api/notification.md. I think core electron covers all the functionality in this package now.

**Comment by clusterberries** [comment]
Thank you, @ccnokes !
