### ISSUE TITLE
Could not locate the bindings file.  Error

### ISSUE THREAD

**Issue by Kronenberg** [CharlieHess/node-mac-notifier#18]
I am using this boilerplate - https://github.com/chentsulin/electron-react-boilerplate
![screen shot 2018-01-16 at 11 38 19 am](https://user-images.githubusercontent.com/13053374/34981967-c8ed6076-fab1-11e7-8a92-10d197493093.png)

I just require this module

**Comment by CharlieHess** [comment]
After building, search in your `node_modules/node-mac-notifier` directory for the `Notification.node` bindings file. That needs to make it into the build output directory. This should be an issue on `electron-react-boilerplate` if they're using this module.
