### ISSUE TITLE
Copy response string before notification goes out of scope

### ISSUE THREAD

**Issue by CharlieHess** [CharlieHess/node-mac-notifier#7]
Need to make a copy of the response [here](https://github.com/CharlieHess/node-mac-notifier/blob/master/notification_center_delegate.mm#L49) and dispose of it [here](https://github.com/CharlieHess/node-mac-notifier/blob/master/notification_center_delegate.mm#L18). Otherwise the `response` will disappear when its parent `notification` goes out of scope, resulting in garbage that is _sometimes_ correct, because we're accessing that memory immediately after.

**Comment by CharlieHess** [comment]
Fixed [here](https://github.com/CharlieHess/node-mac-notifier/commit/c80bfd2dfd40200892ed7f2ab6672df56e9d512b). cc @ccnokes

**Comment by CharlieHess** [comment]
Update to v0.0.9 for the fix.

**Comment by ccnokes** [comment]
nice, thanks!
